#ifndef LAYOUT_H
#define LAYOUT_H

#include "config.hpp"
#include "sprites.hpp"

#define TOTAL_WIDTH SCREEN_WIDTH
#define TOTAL_HEIGHT SCREEN_HEIGHT

#define SECTION_SPRITES_X 0
#define SECTION_SPRITES_Y 0
#define SECTION_SPRITES_WIDTH TYPE_SPRITE_WIDTH
#define POKESPRITE_H_MARGIN ((SECTION_SPRITES_WIDTH - SPRITE_SIZE) / 2)
#define POKESPRITE_V_MARGIN (POKESPRITE_H_MARGIN / 2)
#define SECTION_SPRITES_HEIGHT (POKESPRITE_V_MARGIN + SPRITE_SIZE + POKESPRITE_V_MARGIN + TYPE_SPRITE_HEIGHT + TYPE_SPRITE_HEIGHT)

#define POKESPRITE_X POKESPRITE_H_MARGIN
#define POKESPRITE_Y POKESPRITE_V_MARGIN
#define POKESPRITE_SIZE SPRITE_SIZE
#define POKEBORDER_X 0
#define POKEBORDER_Y 0
#define POKEBORDER_WIDTH (POKESPRITE_H_MARGIN + POKESPRITE_SIZE + POKESPRITE_H_MARGIN)
#define POKEBORDER_HEIGHT (POKESPRITE_V_MARGIN + POKESPRITE_SIZE + POKESPRITE_V_MARGIN)

#define TYPE1SPRITE_X 0
#define TYPE1SPRITE_Y POKEBORDER_HEIGHT
#define TYPE2SPRITE_X 0
#define TYPE2SPRITE_Y (POKEBORDER_HEIGHT + TYPE_SPRITE_HEIGHT)
#define TYPESPRITE_WIDTH TYPE_SPRITE_WIDTH
#define TYPESPRITE_HEIGHT TYPE_SPRITE_HEIGHT

#define BATTERY_SECTION_X 0
#define BATTERY_SECTION_Y SECTION_SPRITES_HEIGHT
#define BATTERY_SECTION_WIDTH TOTAL_WIDTH
#define BATTERY_SECTION_HEIGHT (TOTAL_HEIGHT - SECTION_SPRITES_HEIGHT)

#define MARGIN_FROM_SPRITES 20
#define MARGIN_FROM_TOP 80
#define MARGIN_FROM_RIGHT 10
#define SECTION_INFO_X (SECTION_SPRITES_WIDTH + MARGIN_FROM_SPRITES)
#define SECTION_INFO_Y MARGIN_FROM_TOP
#define SECTION_INFO_WIDTH (TOTAL_WIDTH - SECTION_SPRITES_WIDTH - MARGIN_FROM_RIGHT)
#define SECTION_INFO_HEIGHT (TOTAL_HEIGHT - BATTERY_SECTION_HEIGHT - TYPESPRITE_HEIGHT - TYPESPRITE_HEIGHT - MARGIN_FROM_TOP)

#endif